# Generated by Django 3.1.3 on 2023-03-17 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20230317_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='ordered_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
